### ISSUE TITLE
problem on install

### ISSUE THREAD

**Issue by platini76** [Nekmo/amazon-dash#105]
pi@raspberry:~ $ sudo python -m amazon_dash.install
/usr/bin/python: No module named amazon_dash

**Comment by Nekmo** [comment]
Have you executed `pip install amazon-dash`?

Please follow the guide to create issues.
https://github.com/Nekmo/amazon-dash/blob/develop/.github/ISSUE_TEMPLATE.md

**Comment by platini76** [comment]
pi@raspberry:~ $ pip install amazon-dash
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: amazon-dash in /usr/local/lib/python3.5/dist-packages (1.3.1)
Requirement already satisfied: scapy>=2.4.0; python_version > "3.0" in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (2.4.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (2.6.0)
Requirement already satisfied: requests in ./.local/lib/python3.5/site-packages (from amazon-dash) (2.19.1)
Requirement already satisfied: PyYAML>=3.0 in ./.local/lib/python3.5/site-packages (from amazon-dash) (3.13)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from amazon-dash) (6.6)
Requirement already satisfied: click-default-group in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (1.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python3.5/site-packages (from requests->amazon-dash) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in ./.local/lib/python3.5/site-packages (from requests->amazon-dash) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.5/site-packages (from requests->amazon-dash) (2018.10.15)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in ./.local/lib/python3.5/site-packages (from requests->amazon-dash) (1.23)

**Comment by platini76** [comment]
and after: 
pi@raspberry:~ $ sudo python -m amazon_dash.install
/usr/bin/python: No module named amazon_dash

**Comment by Nekmo** [comment]
Test installing amazon-dash using sudo:

```
$ sudo pip install amazon-dash
```

And then:

```
$ sudo python -m amazon_dash.install
```

**Comment by platini76** [comment]
[pi@raspberry:~ $ sudo pip install amazon-dash
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: amazon-dash in /usr/local/lib/python3.5/dist-packages (1.3.1)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from amazon-dash) (6.6)
Requirement already satisfied: click-default-group in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (1.2)
Requirement already satisfied: scapy>=2.4.0; python_version > "3.0" in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (2.4.0)
Requirement already satisfied: PyYAML>=3.0 in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (3.13)
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (2.19.1)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (2.6.0)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests->amazon-dash) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests->amazon-dash) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests->amazon-dash) (2018.10.15)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests->amazon-dash) (3.0.4)
pi@raspberry:~ $ sudo python -m amazon_dash.install
/usr/bin/python: No module named amazon_dash

**Comment by Nekmo** [comment]
Pip is using Python3. It is possible that your distribution uses Python 2 by default along with Pip Python 3. Check your version of Python:

```
python --version
```

If the default Python version is 2.7, use this to force python3:

```
sudo python3 -m amazon_dash.install
```

If this is the problem, and you are using a standard installation of your distribution, tell me the name of your distribution. This could be a problem of your distribution.

**Comment by platini76** [comment]
perfect!!! thanks! now it is installed... but don't work...
what I make wrong?? I am struggling since yesterday...

[Error] Amazon Dash Exception (InvalidConfig):
nov 04 16:38:42 raspberry env[4297]: The configuration file is invalid (/etc/amazon-dash.yml). Check the file and read the documentation. 'access', 'event', 'homeassistant', 'name' do not match any of the regexes: '^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$'
nov 04 16:38:42 raspberry env[4297]: Failed validating 'additionalProperties' in schema['properties']['devices']:
nov 04 16:38:42 raspberry env[4297]:     {'additionalProperties': False,
nov 04 16:38:42 raspberry env[4297]:      'patternProperties': {'^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$': {'properties': {'body': {'type': 'string'},
nov 04 16:38:42 raspberry env[4297]:                                                                                        'cmd': {'type': 'string'},
nov 04 16:38:42 raspberry env[4297]:                                                                                        'confirmation': {'type': 'string'},
nov 04 16:38:42 raspberry env[4297]:                                                                                        'content-type': {'type': 'string'},
nov 04 16:38:42 raspberry env[4297]:                                                                                        'cwd': {'type': 'string'},
nov 04 16:38:42 raspberry env[4297]:                                                                                        'event': {'type': 'string'},
nov 04 16:38:42 raspberry env[4297]:                                                                                        'headers': {'type': 'object'}

**Comment by Nekmo** [comment]
Hello, about the previous problem, what is your distribution?

**Comment by platini76** [comment]
debian 9 raspbian

**Comment by platini76** [comment]
my config:

settings:
  # On seconds. Minimum time that must pass between pulsations.
  delay: 10
devices:
  ## Example of how to execute a system command
    **:**:**:**:**:**:  # You can know the mac of your device with the discovery command
    name: Tampax
    homeassistant: 192.168.0.15 # Address to the hass server
    access: ************
    event: system_log.clear  # Event name to send


[Error] Amazon Dash Exception (InvalidConfig):
nov 04 16:56:19 raspberry env[7712]: The configuration file is invalid (/etc/amazon-dash.yml). Check the file and read the documentation. None is not of type 'object'
nov 04 16:56:19 raspberry env[7712]: Failed validating 'type' in schema['properties']['devices']['patternProperties']['^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$']:

**Comment by Nekmo** [comment]
Hello, the contents of the device block must be indented like this:

```
settings:
  delay: 10
devices:
    **:**:**:**:**:**:  # You can know the mac of your device with the discovery command
      name: Tampax
      homeassistant: 192.168.0.15 # Address to the hass server
      access: ************
      event: system_log.clear  # Event name to send
```
Please check the documentation.

**Comment by Nekmo** [comment]
The configuration you have pasted is:
```
settings:
  delay: 10
devices:
    **:**:**:**:**:**:  # You can know the mac of your device with the discovery command
    name: Tampax
    homeassistant: 192.168.0.15 # Address to the hass server
    access: ************
    event: system_log.clear  # Event name to send
```

Instead this:
```
settings:
  delay: 10
devices:
  **:**:**:**:**:**:  # You can know the mac of your device with the discovery command
    name: Tampax
    homeassistant: 192.168.0.15 # Address to the hass server
    access: ************
    event: system_log.clear  # Event name to send
```

Indentation is important in yaml.
