### ISSUE TITLE
Add support for "services" of Home Assistant

### ISSUE THREAD

**Issue by RyuzakiKK** [Nekmo/amazon-dash#109]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

#### Description

Currently `events` are the only possible way to interact with Home Assistant.
It would be handy if also `services` would be supported.
For example this is a valid request for HA:

`requests.post("https://assistant/api/services/light/toggle", data='{"entity_id": "light.Main_Room"}', headers=headers)`

The advantage is that you don't need to create a new event handler in HA in order to use that.
The documentation is here https://developers.home-assistant.io/docs/en/external_api_rest.html

Maybe a possible configuration for amazon-dash would look like this:

```
devices:
  40:B4:CD:67:A2:E1:
    name: Fairy
    homeassistant: hassio.local
    service: light/toggle
    data: '{"entity_id": "light.Main_Room"}'
```

**Comment by RyuzakiKK** [comment]
I just found out that there is a `call_service` that has the effect of exactly what I was looking for.
https://www.home-assistant.io/docs/configuration/events/#event-call_service

In short it's possible to achieve what I wrote in the first post with:
```
devices:
  40:B4:CD:67:A2:E1:
    name: Fairy
    homeassistant: hassio.local
    event: call_service
    data: '{"domain": "light", "service": "toggle", "service_data": {"entity_id": "light.Main_Room"}}'
```

Given the `call_service` capability, I think that a native `service` support is no more needed.
@Nekmo feel free to close this issue.
