### ISSUE TITLE
Telegram issue: "Error code: 400"

### ISSUE THREAD

**Issue by asiag0** [Nekmo/amazon-dash#122]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

* amazon-dash version: v1.3.2
* Python version: v2.7.13
* Pip & Setuptools version:  9.0.1/33.1.1
* Operating System: raspbian (kernel 4.14.79-v7+ #1159)

- [x] The `pip install` or `setup install` command has been completed without errors
- [x] The `python -m amazon_dash.install` command has been completed without errors
- [x] The `amazon-dash discovery` command works without errors
- [x] I have created/edited the configuration file
- [x] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

I'm trying to set up telegram notification, however, during testing, it returns the error:

> 2019-01-31 08:18:29,335 - amazon-dash - WARNING - Error sending confirmation on device button: Error on telegram confirmation. Error code: 400. Error message: Bad Request: chat not found

Here's my config file:

```
#amazon-dash.yml
# ---------------
settings:
  delay: 10

devices:
    XX:XX:XX:XX:XX:XX: # Angel Soft                                                                                                                                                                                         
      name: button
      confirmation: send-tg
      cmd: date

confirmations:
    send-tg:
      service: telegram
      token: 'TOKEN'
      to: USERID
      is_default: true
```

I think perhaps I'm missing something, but I've checked all the documentation and can't see what I'm missing.  I've verified that my telegram token and user id are both correct.
