### ISSUE TITLE
SSL conection

### ISSUE THREAD

**Issue by juancarloscastro75** [Nekmo/amazon-dash#126]
Hi,

I'm using now a SSL conexion, and the dash has stopped working

sudo amazon-dash test-device 00:FC:xx:xx:xx:xx --config /etc/amazon-dash.yml
Welcome to Amazon-dash v1.3.2 using Python 3.6.7
[Error] Amazon Dash Exception (ExecuteError):
Exception on request to **http**://192.168.3.10:8123/api/events/dash1: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

It is clear that the problem is in the type of connection.
I have verified the documentation, but I do not see how it works:

> **access**: Home Assistant legacy API password (x-ha-access header).
> **verify**: By default True. Validate SSL/TLS certificate on request. To ignore errors (for example self-signed certificate) put false. You can also set the path to the certificate or certificate directory (generate using OpenSSL c_rehash utility). This can be useful if you use self-signed https.

I'm using the verify: false
amazon-dash.yml
```
settings:
  delay: 10
devices:
  00:FC:8B:DD:7C:E3:
    name: Nescafe button
    homeassistant: 192.168.3.10
    event: dash1
    verify: false
    access_token: eyJ0eXAiOiJKV1Qxxxxxxxxxxxxxxxxx

```
Thanks
