### ISSUE TITLE
API call keeps being made without button press

### ISSUE THREAD

**Issue by ljmerza** [Nekmo/amazon-dash#143]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Guideline for bug reports
2019-08-23 16:41:26,674 - amazon-dash - DEBUG   - Living Room Lights device executed (mac 3c:37:86:61:da:2d)

* amazon-dash version: 1.3.2
* Python version: 3.7.2
* Pip & Setuptools version:
* Operating System: docker on ubuntu 16

- [x] The `pip install` or `setup install` command has been completed without errors
- [x] The `python -m amazon_dash.install` command has been completed without errors
- [x] The `amazon-dash discovery` command works without errors
- [x] I have created/edited the configuration file
- [x] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description
Device keep making API call every 5 seconds even though I didn't push the button

```

devices:
  3c:aa:86:61:aa:2d:
    name: Living Room Lights
    url: 'https://example.com/rqtEOUENm/lights'
    method: post
    content-type: json
    body: '{"action": "living_room"}'
```
