### ISSUE TITLE
Provide custom success/failure messages

### ISSUE THREAD

**Issue by chrissv** [Nekmo/amazon-dash#149]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

#### Description

Currently the text for the confirmation is either the output of the command, or a generic **The {} device has been executed successfully**.
This enhancement is to provide custom success and failure text in the yml file for the confirmations, for example:
```
devices:
  78:e1:03:b5:44:aa:
    name: test_button
    cmd: some_command
    ssh: localhost
    confirmation: send-tg
    msg_success: {name} light is turned on
    msg_failure: Something bad happened with {name} - check log
```
(_msg_success_ and _msg_failure_ are the new parameters, as a suggestion)

In addition to the new messages, it would be nice to have some kind of primitive substitutions within the messages for things like the name, and maybe others that would make sense (such as date and time, and output from the cmd).
