### ISSUE TITLE
Confirmations config

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/amazon-dash#34]
Confirmations section:

```
    confirmations:
      telegram-dash-bot:
        service: telegram
        token: 50164****:ABGDgiKEHFTeKnAtBkq0UEeBODdpZY*****
        is_default: false
```

On devices:
```
    devices:
      0C:47:C9:98:4A:12:
        name: Hero
        confirmation: telegram-dash-bot
        user: nekmo
        cmd: spotify
```
