### ISSUE TITLE
Start on boot

### ISSUE THREAD

**Issue by LimeBlast** [Nekmo/amazon-dash#4]
Hi, what's the best way of making this start on boot?

I'm running it from a Raspberry Pi, and the only way I was able to make it successfully make it run as as root on boot was to add the following line to `/etc/rc.local`:

```
su pi -c 'cd /home/pi/Code/automate && sudo amazon-dash run < /dev/null &'
```

As you can see, this changes to the directory that contains the `amazon-dash.yml` file, then runs `sudo amazon-dash run`. I'm not sure what the rest of the line does, or if it's required, but this whole approach seems like overkill, and I can't help but feel it's wrong.

I guess I have two question in that case:

- is there a way of running the script by passing in a path to the config file (rather than having to cd into the directory that contains the file)
- is there a better way of running the script on boot, maybe via init.d or something like that?

Thank you.

**Comment by Nekmo** [comment]
Hello, there is already a parameter to define the path to the configuration file. This parameter is `--config`. You can see it by running `--help`. However, I think it is necessary to explain its use.

Init.d is dead. His successor is Systemd. There is an example of use in the services folder of the project.
https://github.com/Nekmo/amazon-dash/blob/master/services/amazon-dash.service

However, if your computer uses another system, you can read the Systemd example and adapt it. Feel free to do a pull-request.

To add to Systemd:

1. Copy `amazon-dash.service` to `/etc/systemd/system/`.
2. Create your config file in `/etc/amazon-dash.yml`.
3. Enable your service with `sudo systemctl enable amazon-dash`
4. Start your service with  `sudo systemctl start amazon-dash`

Thank you for your comments. If you think my answer will solve your problem, please close the report.

**Comment by LimeBlast** [comment]
As requested in #1, here are the errors I'm getting:

```
usage: amazon-dash [-h] [--config CONFIG] [--warning] [--quiet] [--debug]
                   [--verbose]
                   {discovery,run} ...
amazon-dash: error: unrecognized arguments: --config /home/pi/Code/automate/amazon-dash.yml
```

This is the output from both `sudo amazon-dash --config /home/pi/Code/automate/amazon-dash.yml` and `sudo amazon-dash run --config /home/pi/Code/automate/amazon-dash.yml `

----------------------

I've not yet tried your Systemd suggestion, I'll be doing that shortly.

**Comment by Nekmo** [comment]
Try:
```
sudo amazon-dash --config /home/pi/Code/automate/amazon-dash.yml run
```

**Comment by LimeBlast** [comment]
@Nekmo Thank you for your help with this.

The above code worked great for running the tool with a custom config path, but I'm still not having any luck with getting the systemd suggestion working.

I've created the files as described, and run the required commands, but it's not working.

I've run `sudo journalctl -u amazon-dash` to see if I can find out what's wrong, which is giving me the following:

```
May 23 12:39:45 oxygen systemd[1]: amazon-dash.service holdoff time over, scheduling restart.
May 23 12:39:45 oxygen systemd[1]: Stopping Amazon Dash service...
May 23 12:39:45 oxygen systemd[1]: Starting Amazon Dash service...
May 23 12:39:45 oxygen systemd[1]: Started Amazon Dash service.
May 23 12:39:45 oxygen systemd[1]: amazon-dash.service: main process exited, code=exited, status=203/EXEC
May 23 12:39:45 oxygen systemd[1]: Unit amazon-dash.service entered failed state.
May 23 12:39:49 oxygen systemd[1]: amazon-dash.service holdoff time over, scheduling restart.
May 23 12:39:49 oxygen systemd[1]: Stopping Amazon Dash service...
May 23 12:39:49 oxygen systemd[1]: Starting Amazon Dash service...
May 23 12:39:49 oxygen systemd[1]: Started Amazon Dash service.
May 23 12:39:49 oxygen systemd[1]: amazon-dash.service: main process exited, code=exited, status=203/EXEC
May 23 12:39:49 oxygen systemd[1]: Unit amazon-dash.service entered failed state.
```

I've also tried changing [this line](https://github.com/Nekmo/amazon-dash/blob/master/services/amazon-dash.service#L6) to include `run` on the end, but that gives the same errors as above.


Just for reference purposes, here's the amazon-dash.yml file I'm using. It works fine when running the `amazon-dash` command manually:

```
settings:
  delay: 10
devices:
  ac:63:be:7b:85:8c:
    name: Right Guard # armchair
    user: pi
    cmd: /usr/bin/python3 /home/pi/Code/automate/armchair.py
  0c:47:c9:e7:46:e5:
    name: Fiesta kicthen towel # desk
    user: pi
    cmd: /usr/bin/python3 /home/pi/Code/automate/desk.py
  ac:63:be:7c:60:90:
    name: Biona Organic # lunch
    user: pi
    cmd: /usr/bin/python3 /home/pi/Code/automate/lunch.py
  ac:63:be:39:43:68:
    name: Nescafe Dolce Gusto # goodnight
    user: pi
    cmd: /usr/bin/python3 /home/pi/Code/automate/goodnight.py
```
