### ISSUE TITLE
Access password-protected URL

### ISSUE THREAD

**Issue by WayneManion** [Nekmo/amazon-dash#41]
I'd like the script to GET a password-protected URL when the button is pressed. Is this supported in the script or do I have to run a wget with the user name and password in the command?

Thanks

* amazon-dash version: 1.0.0
* Python version: 
* Operating System: Ubuntu Linux 17.10

**Comment by Nekmo** [comment]
Hello, you have two ways with the current version (for basic auth authentication):

- Use url executor with Authorization header
- Use cmd executor with curl

```
# amazon-dash.yml
# ---------------
settings:
  delay: 10
devices:
  AC:63:BE:67:B2:F1:
    name: Url example
    url: 'http://domain.com/path/to/webhook'
    headers: {"Authorization": "Basic QWxhZGRpbjpPcGVuU2VzYW1l"}
  AC:63:BE:67:B2:F2:
    name: Cmd example
    cmd: "curl -u user:pass http://domain.com/path/to/webhook"
```
`QWxhZGRpbjpPcGVuU2VzYW1l` is `Aladdin:OpenSesame` in base64.

However this new option is a good idea and will be added in the next release.

Greetings.
