### ISSUE TITLE
':' in url

### ISSUE THREAD

**Issue by four2six** [Nekmo/amazon-dash#45]
* amazon-dash version: v1.0.2
* Python version: 2.7.3.
* Operating System: Raspbian

I tried to call a url with a port number (http://x.x.x.x:port/restofurl). 

it gives me
`[Error] Amazon Dash Exception (InvalidConfig):
The configuration file is invalid (/home/pi/amazon-dash.yml). Check the file and read the documentation. 'name', 'url' do not match any of the regexes: '^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$'
`
are there any other ways to use a certain port in a url?

**Comment by Nekmo** [comment]
Please paste your configuration. It seems that It is validating the url in the field for the mac address.

```
        "devices": {
            "type": "object",
            "properties": {
                "/": {}
            },
            "patternProperties": {
                "^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "cmd": {
                            "type": "string"
                        },
                        "user": {
                            "type": "string",
                        },
                        "cwd": {
                            "type": "string",
                        },
                        "url": {
                            "type": "string"
                        },
                        "method": {
                            "type": "string",
                            "oneOf": [
                                {"pattern": "GET|get"},
                                {"pattern": "HEAD|head"},
                                {"pattern": "POST|post"},
                                {"pattern": "PUT|put"},
                                {"pattern": "DELETE|delete"},
                                {"pattern": "CONNECT|connect"},
                                {"pattern": "OPTIONS|options"},
                                {"pattern": "trace|trace"},
                                {"pattern": "PATCH|patch"},
                            ]
                        },
                        "headers": {
                            "type": "object",
                        },
                        "content-type": {
                            "type": "string"
                        },
                        "body": {
                            "type": "string"
                        },
                        "homeassistant": {
                            "type": "string"
                        },
                        "event": {
                            "type": "string"
                        },
                        "confirmation": {
                            "type": "string",
                        }
                    },
                }
            },
            "additionalProperties": False,

        },
```

**Comment by four2six** [comment]
```
settings:
  delay: 10
devices:
  ad:62:b1:49:c4:33:
  name:  dash_gbc
  url: 'http://192.168.2.123:8080/json.htm?type=command&param=switchlight&idx=1234&switchcmd=On'
```

**Comment by Nekmo** [comment]
You need to indent the device block:

```
settings:
  delay: 10
devices:
  ad:62:b1:49:c4:33:
    name:  'dash_gbc'
    url: 'http://192.168.2.123:8080/json.htm?type=command&param=switchlight&idx=1234&switchcmd=On'
```

http://docs.nekmo.org/amazon-dash/config_file.html
