### ISSUE TITLE
Dash Button not discovered / caught

### ISSUE THREAD

**Issue by ostpol** [Nekmo/amazon-dash#51]
* amazon-dash version: 1.0.3
* Python version: 3.4
* Operating System: Linux raspberrypi 4.9.41+ #1023 Tue Aug 8 15:47:12 BST 2017 armv6l GNU/Linux

### Description

When I run `amazon-dash discovery,` several devices (Echo, FireTV...), except the button, are shown. I grabbed the MAC from my routers interface and put it into /etc/amazon-dash.yaml. Sadly the Dash Button still isn't caught when amazon-dash is running, so nothing happens when the button is pressed.

### What I Did

```
settings:
  # On seconds. Minimum time that must pass between pulsations.
  delay: 10
devices:
   ## Example of how to execute a url
 ac:63:be:b5:20:e6:
    name: ShitButton
    url: 'http://192.168.1.50/cm?user=admin&password=pass&cmnd=Power%20Toggle'  # Url to execute
    method: get  # HTTP method. By default GET

```

Are there new Dash Button models which use other communication methods or something?

Thanks,
T
