### ISSUE TITLE
Request to url

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/amazon-dash#6]
Implement new way to execute commands: `url`. Instead of using the `cmd` parameter, use `url`:

```
devices:
  0C:47:C9:98:4A:12:
    url: http://my-domain/api/
```

Long example: 
```yml
# amazon-dash.yml
# ---------------
settings:
  delay: 10
devices:
  0C:47:C9:98:4A:12:
    name: Execute API url
    url: http://my-domain/api/
    method: post
    content-type: json
    body: '{"key": "value"}'
```

| Name         | Description               | Default    |
|--------------|---------------------------|------------|
| url          | Url to request            | <required> |
| method       | HTTP method               | GET        |
| content-type | HTTP Content-Type Header* | **         |
| body         | Request payload           | <empty>    |

`*` Aliases available: `form = application/x-www-form-urlencoded`. `json = application/json`. `plain = text/plain`.
`**` Only available if Body is defined. If body is defined, default is **form**.
