### ISSUE TITLE
[Error] Amazon Dash Exception (InvalidConfig):

### ISSUE THREAD

**Issue by macruz21** [Nekmo/amazon-dash#60]
* amazon-dash version:1.0.4
* Python version:3.6.4
* Operating System: debian 9

### Description
This configuration doesn't work:
# amazon-dash.yml                                                                                                      
# ---------------                                                                                                      
settings:                                                                                                              
  delay: 10                                                                                                            
devices:                                                                                                               
    6c:56:97:xx:xx:xx:                                                                                                 
    name: Ariel                                                                                                        
    user: root                                                                                                         
    cmd: curl -X POST https://maker.ifttt.com/trigger/ventilador_off/with/key/xxxxxxxxxxxxxxxxxxxxxxxx

### What I Did
When execute this command:
amazon-dash --config /etc/amazon-dash.yml
[Error] Amazon Dash Exception (InvalidConfig):
The configuration file is invalid (/etc/amazon-dash.yml). Check the file and read the documentation. None is not of type 'object'
The app show this error: Failed validating 'type' in schema['properties']['devices']['patternProperties']['^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$']:
    {'properties': {'body': {'type': 'string'},
                    'cmd': {'type': 'string'},
                    'confirmation': {'type': 'string'},
                    'content-type': {'type': 'string'},
                    'cwd': {'type': 'string'},
                    'event': {'type': 'string'},
                    'headers': {'type': 'object'},
                    'homeassistant': {'type': 'string'},
                    'method': {'oneOf': [{'pattern': 'GET|get'},
                                         {'pattern': 'HEAD|head'},
                                         {'pattern': 'POST|post'},
                                         {'pattern': 'PUT|put'},
                                         {'pattern': 'DELETE|delete'},
                                         {'pattern': 'CONNECT|connect'},
                                         {'pattern': 'OPTIONS|options'},
                                         {'pattern': 'trace|trace'},
                                         {'pattern': 'PATCH|patch'}],
                               'type': 'string'},
                    'name': {'type': 'string'},
                    'url': {'type': 'string'},
                    'user': {'type': 'string'}},
     'type': 'object'}

On instance['devices']['6c:56:97:xx:xx:xx']:
    None

I've tried other cmd (url, ifttt,etc) and I've obtained the same result.

**Comment by Nekmo** [comment]
You must tabulate in the configuration file.

Correct:
```
# amazon-dash.yml                                                                                                      
# ---------------                                                                                                      
settings:                                                                                                              
  delay: 10                                                                                                            
devices:                                                                                                               
    6c:56:97:xx:xx:xx:                                                                                                 
      name: Ariel                                                                                                        
      user: root                                                                                                         
      cmd: curl -X POST https://maker.ifttt.com/trigger/ventilador_off/with/key/xxxxxxxxxxxxxxxxxxxxxxxx
```

Incorrect:

```
# amazon-dash.yml                                                                                                      
# ---------------                                                                                                      
settings:                                                                                                              
  delay: 10                                                                                                            
devices:                                                                                                               
    6c:56:97:xx:xx:xx:                                                                                                 
    name: Ariel                                                                                                        
    user: root                                                                                                         
    cmd: curl -X POST https://maker.ifttt.com/trigger/ventilador_off/with/key/xxxxxxxxxxxxxxxxxxxxxxxx
```
