### ISSUE TITLE
Toml configuration

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/amazon-dash#64]
```toml
[[devices]]
mac = "0C:47:C9:98:4A:12"
name = "My button name"
  [devices.action]
  action = "cmd"
  command = "ls"
  [devices.confirmation]
  confirmation = "send-telegram"
```
