### ISSUE TITLE
CMD action spawns every 10 seconds with no button press

### ISSUE THREAD

**Issue by adocampo** [Nekmo/amazon-dash#68]
Just discovered this project and it looks amazing!! Muchas gracias Nekmo! ;)

* amazon-dash version: 1.1.0
* Python version: 3.6.6
* Pip & Setuptools version: pip 10.0.1 | setuptools 39.2.0
* Operating System: Arch Linux

### Description
Just installed amazon-dash, following the setup guide through pip (and not the AUR package). I got the mac address of the button and modified the amazon-dash.yml just to change the mac on the example for my button's mac address.

The first thing I noticed was no X application could be started because root user hasn't any DISPLAY available assigned, so I had to modify the yml as follows:
```
settings:
  # On seconds. Minimum time that must pass between pulsations.
  delay: 10
devices:
  ## Example of how to execute a system command
  00:21:6B:10:CE:94:  # You can know the mac of your device with the discovery command
    name: Brabantia # You can put the name you want
    user: adocampo  # System user. Necessary if it is executed as root
    cmd: DISPLAY=:0 spotify  # Command to execute
 ```

Once DISPLAY var was specified, and the systemd unit is started, it launches a spotify instance every 10 seconds (as per delay parameter is specified)... without the press of any button :|  So I have 6 Spotify instances opened after a minute and so on.

The log shows this:
```
jul 30 12:33:02 laptop systemd[1]: Started Amazon Dash service.
jul 30 12:33:02 laptop env[16591]: Welcome to Amazon-dash v1.1.0 using Python 3.6.6
jul 30 12:33:02 laptop env[16591]: Listening for events. Amazon-dash will execute the events associated with the registered buttons.
jul 30 12:33:36 laptop sudo[16604]:     root : TTY=unknown ; PWD=/ ; USER=adocampo ; COMMAND=/bin/sh -c /usr/bin/env bash -c DISPLAY=:0\ spotify
jul 30 12:33:36 laptop sudo[16604]: pam_unix(sudo:session): session opened for user adocampo by (uid=0)
jul 30 12:33:46 laptop sudo[16694]:     root : TTY=unknown ; PWD=/ ; USER=adocampo ; COMMAND=/bin/sh -c /usr/bin/env bash -c DISPLAY=:0\ spotify
jul 30 12:33:46 laptop sudo[16694]: pam_unix(sudo:session): session opened for user adocampo by (uid=0)
jul 30 12:33:57 laptop sudo[16776]:     root : TTY=unknown ; PWD=/ ; USER=adocampo ; COMMAND=/bin/sh -c /usr/bin/env bash -c DISPLAY=:0\ spotify
jul 30 12:33:57 laptop sudo[16776]: pam_unix(sudo:session): session opened for user adocampo by (uid=0)
jul 30 12:34:07 laptop sudo[16858]:     root : TTY=unknown ; PWD=/ ; USER=adocampo ; COMMAND=/bin/sh -c /usr/bin/env bash -c DISPLAY=:0\ spotify
jul 30 12:34:07 laptop sudo[16858]: pam_unix(sudo:session): session opened for user adocampo by (uid=0)
```
I could call a script which could see if there is any spotify process running and if there is none, launch it, but the fact I don't need to press the amazon button to fire the CMD action perhaps is because I'm doing something wrong or perhaps there is a bug somewhere.

Best!
Angel
