### ISSUE TITLE
New yaml config (Amazon Dash 2.0)

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/amazon-dash#71]
```
# amazon-dash 2.0
# --------------------
settings:
  delay: 10
devices:
  - mac: "0C:47:C9:98:4A:12"
    name: "My button name"
    actions:
      - action: "cmd"
        command: "ls"
      - action: "send-telegram"
        condition: "success"
```
