### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by etatus** [Nekmo/amazon-dash#74]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

#### Description

I was trying Home Assistant and I'd like to integrate Amazon Dash buttons, but I don't understand how the configuration works:
```
# amazon-dash.yml
# ---------------
settings:
  delay: 10
devices:
  40:B4:CD:67:A2:E1:
    name: Fairy
    homeassistant: hassio.local
    access: my_homeassistant_password
    event: toggle_kitchen_light
```
Where is "toggle_kitchen_light" defined? Could you provide a more realistic and complete example? From Home Assistant documentation, what I need to specify to launch an action is at least:
- A service (e.g. switch.toggle)
- An entity id (e.g. switch.socket_power)

I don't know how to do this with the 'event' parameter. I could solve this calling Home Assistant API via url as mention in https://github.com/Nekmo/amazon-dash/issues/37, but I'd like to know how the native Home Assistant support works.
